name: CI Pipeline
run-name: CI ğŸš€
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Installing Devbox âš™ï¸
        uses: jetify-com/devbox-install-action@v0.14.0
      - name: Install all dependencies ğŸ“¦
        run: devbox run install
      - name: ğŸ§¹ Linting & Formatting
        run: devbox run lint
      - name: ğŸ§ª Running Tests
        run: devbox run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
