name: CI Pipeline
run-name: CI ğŸš€
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Installing Devbox âš™ï¸
        uses: jetpack-io/devbox-install-action@v0.8.0
      - name: Install all dependencies ğŸ“¦
        run: devbox run install
      - name: ğŸ§¹ Linting & Formatting
        run: devbox run lint && devbox run format
      - name: ğŸ§ª Running Tests
        run: devbox run test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
